include: https://gitlab-templates.ddbuild.io/compute-delivery/v2/compute-delivery.yml

build-docker-image:
  variables:
    EXTRA_ARGS: "-f deployment/docker/Dockerfile"
  extends: .build-docker-image
